moteur_produit_homepage:
    path:     /produit/
    defaults: { _controller: MoteurProduitBundle:Default:index }
moteur_produit_ajout:
    path:     /produit/ajouter
    defaults: { _controller: MoteurProduitBundle:Default:add }
moteur_produit_get:
    path:     /produit/{id_produit}/{id_utilisateur}
    defaults: { _controller: MoteurProduitBundle:Default:get }
moteur_produit_achat:
    path:     /produit/achat/{id_produit}/{id_utilisateur}
    defaults: { _controller: MoteurProduitBundle:Basic:achat }
moteur_produit_note:
    path:     /produit/{id_produit}/{id_utilisateur}/noter
    defaults: { _controller: MoteurProduitBundle:Basic:note }
moteur_produit_affiche:
    path:     /produits/affiche/{id}
    defaults: { _controller: MoteurProduitBundle:Basic:afficher }