parameters:
#    moteur_produit.example.class: Moteur\ProduitBundle\Example

services:
#    moteur_produit.example:
#        class: %moteur_produit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
