moteur_recommendation_homepage:
    path:     /recommendation/{page}/{nombre}
    defaults: { _controller: MoteurRecommendationBundle:Basic:index }
moteur_recommendation_utilisateur:
    path:     /admin/recommendation/{id_utilisateur}
    defaults: { _controller: MoteurRecommendationBundle:Basic:utilisateur }
user_homepage:
    path:     /home
    defaults: { _controller: MoteurRecommendationBundle:Basic:index }  
book_page :
    path:     /book/{id}
    defaults: { _controller: MoteurRecommendationBundle:Basic:book }
search:
    path:     /search/
    defaults: { _controller: MoteurRecommendationBundle:Basic:rechercher }
    

