moteur_recommendation_homepage:
    path:     /recommendation/
    defaults: { _controller: MoteurRecommendationBundle:Default:index }
moteur_recommendation_recherche:
    path:     /recommendation/recherche/{requete}
    defaults: { _controller: MoteurRecommendationBundle:Default:recherche }
moteur_recommendation_utilisateur:
    path:     /recommendation/{id_utilisateur}
    defaults: { _controller: MoteurRecommendationBundle:Default:utilisateur }