moteur_recommendation_homepage:
    path:     /recommendation/{page}/{nombre}
    defaults: { _controller: MoteurRecommendationBundle:Basic:index }
moteur_recommendation_recherche:
    path:     /recommendation/recherche/{requete}
    defaults: { _controller: MoteurRecommendationBundle:Default:recherche }
moteur_recommendation_utilisateur:
    path:     /recommendation/{id_utilisateur}
    defaults: { _controller: MoteurRecommendationBundle:Default:utilisateur }
user_homepage:
    path:     /user
    defaults: { _controller: MoteurRecommendationBundle:Basic:index }  
book_page :
    path:     /book/{id}
    defaults: { _controller: MoteurRecommendationBundle:Basic:book }
search:
    path:     /search/
    defaults: { _controller: MoteurRecommendationBundle:Basic:rechercher }
    

