
moteur_utilisateur_ip:
    path:     /utilisateur/ip/ajout
    defaults: { _controller: MoteurUtilisateurBundle:Default:addIP }
moteur_utilisateur_ajout:
    path:     /utilisateur/ajout
    defaults: { _controller: MoteurUtilisateurBundle:Default:add }
moteur_utilisateur_interet_creer:
    path:     /utilisateur/interet/creer/{nom}
    defaults: { _controller: MoteurUtilisateurBundle:Default:createInteret }
moteur_utilisateur_interet_ajout:
    path:     /utilisateur/interet/ajout
    defaults: { _controller: MoteurUtilisateurBundle:Default:addInteret }
moteur_utilisateur_creer:
    path:     /utilisateur/creer
    defaults: { _controller: MoteurUtilisateurBundle:Basic:creer }
moteur_utilisateur_liste:
    path:     /utilisateur/liste/{page}/{nombre}
    defaults: { _controller: MoteurUtilisateurBundle:Basic:lister }
moteur_utilisateur_affiche:
    path:     /utilisateur/affiche/{nom}/{prenom}
    defaults: { _controller: MoteurUtilisateurBundle:Basic:afficher }
moteur_utilisateur_connecte:
    path:     /connexion
    defaults: { _controller: MoteurUtilisateurBundle:Basic:connecter }
moteur_interet_creer:
    path:     /admin/interet/creer/{nom}
    defaults: { _controller: MoteurUtilisateurBundle:Default:creer }
moteur_interet_liste:
    path:     admin/interet/liste
    defaults: { _controller: MoteurUtilisateurBundle:Default:lister }