parameters:
#    moteur_utilisateur.example.class: Moteur\UtilisateurBundle\Example

services:
#    moteur_utilisateur.example:
#        class: %moteur_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
