moteur_produit:
    resource: "@MoteurProduitBundle/Resources/config/routing.yml"
    prefix:   /moteur/

moteur_utilisateur:
    resource: "@MoteurUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /moteur/

moteur_recommendation:
    resource: "@MoteurRecommendationBundle/Resources/config/routing.yml"
    prefix:   /moteur/
  

