moteur_produit:
    resource: "@MoteurProduitBundle/Resources/config/routing.yml"
    prefix:   /

moteur_utilisateur:
    resource: "@MoteurUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /

moteur_recommendation:
    resource: "@MoteurRecommendationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/
    
  

