_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

# AcmeDemoBundle routes (to be removed)
_acme_demo:
    resource: "@AcmeDemoBundle/Resources/config/routing.yml"

_moteur_recommendation:
    resource: "@MoteurRecommendationBundle/Resources/config/routing.yml"
_moteur_utilisateur:
    resource: "@MoteurUtilisateurBundle/Resources/config/routing.yml"
_moteur_produit:
    resource: "@MoteurProduitBundle/Resources/config/routing.yml"